/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as PropertyAdminRouteImport } from './routes/property-admin'
import { Route as MstRouteImport } from './routes/mst'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPropertyIdRouteImport } from './routes/dashboard.$propertyId'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyAdminRoute = PropertyAdminRouteImport.update({
  id: '/property-admin',
  path: '/property-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MstRoute = MstRouteImport.update({
  id: '/mst',
  path: '/mst',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertyIdRoute = DashboardPropertyIdRouteImport.update({
  id: '/dashboard/$propertyId',
  path: '/dashboard/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mst': typeof MstRoute
  '/property-admin': typeof PropertyAdminRoute
  '/super-admin': typeof SuperAdminRoute
  '/dashboard/$propertyId': typeof DashboardPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mst': typeof MstRoute
  '/property-admin': typeof PropertyAdminRoute
  '/super-admin': typeof SuperAdminRoute
  '/dashboard/$propertyId': typeof DashboardPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mst': typeof MstRoute
  '/property-admin': typeof PropertyAdminRoute
  '/super-admin': typeof SuperAdminRoute
  '/dashboard/$propertyId': typeof DashboardPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mst'
    | '/property-admin'
    | '/super-admin'
    | '/dashboard/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mst'
    | '/property-admin'
    | '/super-admin'
    | '/dashboard/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/mst'
    | '/property-admin'
    | '/super-admin'
    | '/dashboard/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MstRoute: typeof MstRoute
  PropertyAdminRoute: typeof PropertyAdminRoute
  SuperAdminRoute: typeof SuperAdminRoute
  DashboardPropertyIdRoute: typeof DashboardPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-admin': {
      id: '/property-admin'
      path: '/property-admin'
      fullPath: '/property-admin'
      preLoaderRoute: typeof PropertyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mst': {
      id: '/mst'
      path: '/mst'
      fullPath: '/mst'
      preLoaderRoute: typeof MstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$propertyId': {
      id: '/dashboard/$propertyId'
      path: '/dashboard/$propertyId'
      fullPath: '/dashboard/$propertyId'
      preLoaderRoute: typeof DashboardPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MstRoute: MstRoute,
  PropertyAdminRoute: PropertyAdminRoute,
  SuperAdminRoute: SuperAdminRoute,
  DashboardPropertyIdRoute: DashboardPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
